src/views/Patient/MedReqDropDown/MedReqDropDown.tsx

Zaras changes, fixed merge conflict: 
[REMS-415](https://jira.mitre.org/browse/REMS-415)
This task removes the Submit to REMS-Admin button and sends the CDS Hook right when a medication is selected from the dropdown.

fixed merge conflict

---

package-lock.json

Bump semver version to 5.7.2 as suggested by the dependabot.

Bump semver version to 5.7.2 as suggested by the dependabot.

---

src/views/Patient/MedReqDropDown/MedReqDropDown.tsx
src/views/Patient/MedReqDropDown/cdsHooksCards/cdsHooksCard.tsx

Updated cds hooks cards to have better styling and be consistent with the display card. Updated the width to have a max, so it doesn't get as big as before. 
To test (with PR in crd-request generator):
Pull down this branch and crd-request-generator branch 423-display-card-update. Both display cards should be identical and act similar way. 
https://jira.mitre.org/browse/REMS-423

423 cds hooks card styling update

---

src/views/Questionnaire/SmartApp.tsx

Fix issue REMS-463: Fix SMART on FHIR App Questionnaire filter button.

Change the questionnaire filter default to true.

---

src/views/Questionnaire/SmartApp.tsx

Fix prescriber cql prepopulation bug. Use the correct orderResource variable.
[REMS-471](https://jira.mitre.org/browse/REMS-471)

Fix prescriber cql prepopulation bug.

---

src/App.tsx
src/views/Patient/MedReqDropDown/MedReqDropDown.tsx
src/views/Patient/MedReqDropDown/cdsHooksCards/cdsHooksCard.tsx
src/views/Patient/MedReqDropDown/cdsHooksCards/cdsHooksCards.tsx
src/views/Patient/PatientView.tsx
src/views/Questionnaire/QuestionnaireForm.tsx
src/views/Questionnaire/SmartApp.tsx

Fixes the issue where multiple tabs of the same form would not load or be displayed.  You can test that it works by clicking on the same form link multiple times to open several tabs and individually modifying each of the forms.  
This PR adds an ID system to the tabs instead of just relying on the form name.  Tabs are simply numbered starting at 0 and increasing each time a new tab is added.

fix tab bug

---

src/views/Questionnaire/SmartApp.tsx

minor change for usage with the vsac cache changes in the REMS admin.

minor fix for vsac cache

---

.env
package-lock.json
src/views/Patient/MedReqDropDown/MedReqDropDown.tsx
src/views/Patient/PatientView.tsx

> Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.
* Added support for the patient-view hook akin to its implementation in mcode/request-generator
* Send the patient-view hook on page load (since the patient record is available on page load)
* Added a refresh button to resend the patient-view hook after the page loads
1. Run request-generator, rems-admin, pims, and test-ehr on the latest `dev` branch. If you are using Docker, ditto for rems-setup. 
_In request-generator:_
2. Clear the REMS Admin database, the PIMS database, and the EHR QuestionnaireResponses. You can do this by …

Update patient status UI

---

src/views/Questionnaire/QuestionnaireForm.tsx
src/views/Questionnaire/SmartApp.tsx

Fix issues with required fields not updating when changes are made, and "Ignore required fields" button not working.
[REMS-571](https://jira.mitre.org/browse/REMS-571)

Fix issues with checking required fields

---

src/views/Questionnaire/SmartApp.tsx

fixes null alert due to discrepancy between http/https.

fixes null alert due to https/http variance in vsac

---

src/views/Patient/MedReqDropDown/MedReqDropDown.css
src/views/Patient/MedReqDropDown/MedReqDropDown.tsx
src/views/Patient/MedReqDropDown/etasuStatus/EtasuStatus.tsx
src/views/Patient/MedReqDropDown/etasuStatus/__test__/EtasuStatus.test.tsx
src/views/Patient/MedReqDropDown/pharmacyStatus/PharmacyStatus.tsx
src/views/Patient/MedReqDropDown/pharmacyStatus/__test__/PharmacyStatus.test.tsx

Changes the buttons for etasu and pharmacy status to reflect their current status without needing to click on the buttons first.
[REMS-580](https://jira.mitre.org/browse/REMS-580)

add new ui for buttons

---

package-lock.json

Dependabot Bump IP changes from v1.1.8 -> v1.1.9
[original PR from Dependabot](https://github.com/mcode/rems-smart-on-fhir/pull/75)
created new PR to merge into dev instead of main
Please include the Jira Ticket Number and Link for this issue/task.

Dependabot Bump Ip 1.1.9

---

src/views/Patient/MedReqDropDown/cdsHooksCards/cdsHooksCard.tsx
src/views/Patient/MedReqDropDown/cdsHooksCards/cdsHooksCards.tsx

Add support for Suggestions within the CDS Hooks Card. This will enable saving Tasks back to the EHR needsd by the task management features.
[REMS-593](https://jira.mitre.org/browse/REMS-593)

Support Card Suggestions

---

src/views/Patient/MedReqDropDown/etasuStatus/EtasuStatus.tsx

fixes error with auth number
[REMS-670](https://jira.mitre.org/browse/REMS-670)

add auth num

---

src/views/Patient/MedReqDropDown/MedReqDropDown.tsx

Update smart on fhir app to have etasu calls work when there is a medication reference and not medication codable concept. 
To Test:
Alice smith with turalio is an example of this. Go through normal workflow and etasu call should work on both rems-admin and smart on fhir. 
https://jira.mitre.org/browse/REMS-689 

689 etasu call

---

.env
README.md

Updates the readme to be more comprehensive. Note that the base branch is `use-vite` instead of `dev`, this will be updated once `use-vite` is merged, or if this request is merged first. 
[REMS-698](https://jira.mitre.org/browse/REMS-698)

updated readme

---

src/views/Questionnaire/QuestionnaireForm.css
src/views/Questionnaire/SmartApp.tsx

Small update to fix css of 'form help' link on questionnaire. After the 508 compliant styling updates, the background is now grey so the default white text doesn't show up. 
- no ticket

Update styling of form help link in questionnaire

---

package-lock.json
package.json

Update vite to 5.4.19 to fix Vite Arbitrary File Read vulnerability (CVE-2025-30208)
Please include the Jira Ticket Number and Link for this issue/task.

update vite to 5.4.19

---

.github/pull_request_template.md
.github/workflows/ci-workflow.yml
.github/workflows/docker-cd-dev.yml
.github/workflows/docker-cd.yml
.github/workflows/docker-ci.yml
.github/workflows/docker-tag-cd.yml
index.html
src/App.css
src/index.css
src/views/Help/Help.css
src/views/Patient/MedReqDropDown/etasuStatus/EtasuStatus.css
src/views/Patient/MedReqDropDown/pharmacyStatus/PharmacyStatus.css
src/views/Questionnaire/QuestionnaireForm.css
src/views/Questionnaire/components/PatientSelect/PatientStyles.css
vite.config.ts

vite updates
Please include the Jira Ticket Number and Link for this issue/task.

vite updates

---

package-lock.json
package.json
src/views/Patient/MedReqDropDown/cdsHooksCards/CdsHooksCard.tsx
src/views/Patient/MedReqDropDown/etasuStatus/__test__/EtasuStatus.test.tsx
src/views/Patient/PatientView.tsx
src/views/Questionnaire/QuestionnaireForm.tsx

Update prefetch to include pharmacy info. Run with updated submodule branch.
Please include the Jira Ticket Number and Link for this issue/task.

Update cds hooks pharmacy ref
